[package]
name = "json"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.42.0", features = ["full"] }
parse-book-source = { path = "../../" }
anyhow = "1.0.94"
serde_json = "1.0.133"
